name: Transaction App Build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        with:
          ref: refs/heads/main
      - name: install
        run: |
          npm install
          npm install --prefix ./client
      - name: build
        run: |
          npm run build --prefix ./client
      - name: start server
        run: |
           npm start &
           npm start --prefix ./client &
      - name: uat
        uses: cypress-io/github-action@v1